<?php

/**
 * Created by PhpStorm.
 * User: Carles
 * Date: 12/09/2016
 * Time: 14:22
 */
class Producto extends GrupoFiguras
{
    public function __construct($nombre)
    {
        parent::__construct($nombre);
    }
    public function agregar(Figura $fig)
    {
        parent::agregar($fig); // TODO: Change the autogenerated stub
        print ('no se puede agregar objeto');
    }
    public function eliminar(Figura $fig)
    {
        parent::eliminar($fig); // TODO: Change the autogenerated stub
        print ('no se puede eliminar objeto');
    }
    public function mostrar($num)
    {
        parent::mostrar($num); // TODO: Change the autogenerated stub
        print ('-'. ' '. $this->nombre);
    }
}